"""schema inicial

Revision ID: 0001
Revises:
Create Date: 2026-08-15 13:51:41.722677
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '0001'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admin_usuarios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(), nullable=False),
    sa.Column('login', sa.String(), nullable=False),
    sa.Column('senha_hash', sa.String(), nullable=False),
    sa.Column('papel', sa.Enum('gerencia', 'almoxarifado', name='papeladmin'), nullable=True),
    sa.Column('ativo', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('login')
    )
    op.create_table('clientes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(), nullable=False),
    sa.Column('endereco', sa.String(), nullable=True),
    sa.Column('observacoes', sa.Text(), nullable=True),
    sa.Column('imagem_rota_cabo', sa.String(), nullable=True),
    sa.Column('criado_em', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('contas_financeiras',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tipo', sa.Enum('pagar', 'receber', name='tipoconta'), nullable=False),
    sa.Column('descricao', sa.String(), nullable=False),
    sa.Column('valor', sa.Float(), nullable=False),
    sa.Column('vencimento', sa.String(), nullable=False),
    sa.Column('categoria', sa.String(), nullable=True),
    sa.Column('status', sa.Enum('pendente', 'pago', 'cancelado', name='statusconta'), nullable=True),
    sa.Column('data_pagamento', sa.String(), nullable=True),
    sa.Column('observacoes', sa.Text(), nullable=True),
    sa.Column('criada_em', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('materiais',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(), nullable=False),
    sa.Column('categoria', sa.String(), nullable=True),
    sa.Column('unidade', sa.String(), nullable=True),
    sa.Column('qtd_atual', sa.Float(), nullable=True),
    sa.Column('qtd_minima', sa.Float(), nullable=True),
    sa.Column('custo_unitario', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tecnicos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(), nullable=False),
    sa.Column('login', sa.String(), nullable=False),
    sa.Column('pin_hash', sa.String(), nullable=False),
    sa.Column('ativo', sa.Boolean(), nullable=True),
    sa.Column('aprovado', sa.Boolean(), nullable=True),
    sa.Column('is_adm', sa.Boolean(), nullable=True),
    sa.Column('telefone', sa.String(), nullable=True),
    sa.Column('data_contratacao', sa.String(), nullable=True),
    sa.Column('foto_perfil', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('login')
    )
    op.create_table('estoque_pessoal',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tecnico_id', sa.Integer(), nullable=False),
    sa.Column('material_id', sa.Integer(), nullable=False),
    sa.Column('qtd_atual', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['material_id'], ['materiais.id'], ),
    sa.ForeignKeyConstraint(['tecnico_id'], ['tecnicos.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tecnico_id', 'material_id', name='uq_estoque_pessoal')
    )
    op.create_table('ferramentas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(), nullable=False),
    sa.Column('codigo_patrimonio', sa.String(), nullable=True),
    sa.Column('categoria', sa.Enum('ferramenta', 'epi', name='categoriaferramenta'), nullable=True),
    sa.Column('status', sa.Enum('disponivel', 'em_transito', 'com_tecnico', 'manutencao', 'baixada', name='statusferramenta'), nullable=True),
    sa.Column('tecnico_atual_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['tecnico_atual_id'], ['tecnicos.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('codigo_patrimonio')
    )
    op.create_table('monitor_clientes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cliente_id', sa.Integer(), nullable=False),
    sa.Column('codigo', sa.String(), nullable=False),
    sa.Column('ativo', sa.Boolean(), nullable=False),
    sa.Column('criado_em', sa.DateTime(), nullable=False),
    sa.Column('atualizado_em', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['cliente_id'], ['clientes.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cliente_id'),
    sa.UniqueConstraint('codigo')
    )
    op.create_table('ordens_servico',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tecnico_id', sa.Integer(), nullable=True),
    sa.Column('cliente_id', sa.Integer(), nullable=True),
    sa.Column('tipo', sa.Enum('instalacao', 'manutencao', 'preventiva', name='tipoos'), nullable=False),
    sa.Column('cliente_local', sa.String(), nullable=False),
    sa.Column('nome_cliente', sa.String(), nullable=True),
    sa.Column('endereco', sa.String(), nullable=True),
    sa.Column('prioridade', sa.Boolean(), nullable=True),
    sa.Column('observacoes', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('pendente', 'deslocamento', 'em_andamento', 'fechada', name='statusos'), nullable=True),
    sa.Column('criada_por_admin', sa.Boolean(), nullable=True),
    sa.Column('data_abertura', sa.DateTime(), nullable=True),
    sa.Column('data_deslocamento', sa.DateTime(), nullable=True),
    sa.Column('data_inicio', sa.DateTime(), nullable=True),
    sa.Column('data_fechamento', sa.DateTime(), nullable=True),
    sa.Column('pdf_path', sa.String(), nullable=True),
    sa.Column('lat_deslocamento', sa.Float(), nullable=True),
    sa.Column('lon_deslocamento', sa.Float(), nullable=True),
    sa.Column('lat_inicio', sa.Float(), nullable=True),
    sa.Column('lon_inicio', sa.Float(), nullable=True),
    sa.Column('lat_fim', sa.Float(), nullable=True),
    sa.Column('lon_fim', sa.Float(), nullable=True),
    sa.Column('checklist_limpar_conector', sa.Boolean(), nullable=True),
    sa.Column('checklist_testar_sinal', sa.Boolean(), nullable=True),
    sa.Column('checklist_verificar_otdr', sa.Boolean(), nullable=True),
    sa.Column('client_uuid', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['cliente_id'], ['clientes.id'], ),
    sa.ForeignKeyConstraint(['tecnico_id'], ['tecnicos.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('client_uuid')
    )
    op.create_table('solicitacoes_material',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tecnico_id', sa.Integer(), nullable=False),
    sa.Column('material_id', sa.Integer(), nullable=False),
    sa.Column('quantidade', sa.Float(), nullable=False),
    sa.Column('observacao', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('pendente', 'aprovada', 'rejeitada', name='statussolicitacao'), nullable=True),
    sa.Column('data_solicitacao', sa.DateTime(), nullable=True),
    sa.Column('data_resposta', sa.DateTime(), nullable=True),
    sa.Column('client_uuid', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['material_id'], ['materiais.id'], ),
    sa.ForeignKeyConstraint(['tecnico_id'], ['tecnicos.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('client_uuid')
    )
    op.create_table('avisos_ferramentas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ferramenta_id', sa.Integer(), nullable=False),
    sa.Column('tecnico_id', sa.Integer(), nullable=False),
    sa.Column('descricao', sa.Text(), nullable=False),
    sa.Column('status', sa.Enum('aberto', 'resolvido', name='statusaviso'), nullable=True),
    sa.Column('data_criacao', sa.DateTime(), nullable=True),
    sa.Column('data_resolucao', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['ferramenta_id'], ['ferramentas.id'], ),
    sa.ForeignKeyConstraint(['tecnico_id'], ['tecnicos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('fotos_ordem',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ordem_id', sa.Integer(), nullable=False),
    sa.Column('caminho', sa.String(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('client_uuid', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['ordem_id'], ['ordens_servico.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('client_uuid')
    )
    op.create_table('monitor_unidades',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('monitor_cliente_id', sa.Integer(), nullable=False),
    sa.Column('codigo', sa.String(), nullable=False),
    sa.Column('nome', sa.String(), nullable=False),
    sa.Column('cidade', sa.String(), nullable=False),
    sa.Column('estado', sa.String(), nullable=True),
    sa.Column('ativo', sa.Boolean(), nullable=False),
    sa.Column('criado_em', sa.DateTime(), nullable=False),
    sa.Column('atualizado_em', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['monitor_cliente_id'], ['monitor_clientes.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('codigo')
    )
    op.create_table('movimentacoes_estoque',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('material_id', sa.Integer(), nullable=False),
    sa.Column('ordem_id', sa.Integer(), nullable=True),
    sa.Column('quantidade', sa.Float(), nullable=False),
    sa.Column('tipo', sa.Enum('saida', 'entrada', 'ajuste', name='tipomovimentacao'), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('client_uuid', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['material_id'], ['materiais.id'], ),
    sa.ForeignKeyConstraint(['ordem_id'], ['ordens_servico.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('client_uuid')
    )
    op.create_table('transferencias',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tecnico_id', sa.Integer(), nullable=False),
    sa.Column('tipo', sa.Enum('material', 'ferramenta', name='tipotransferencia'), nullable=False),
    sa.Column('material_id', sa.Integer(), nullable=True),
    sa.Column('quantidade', sa.Float(), nullable=True),
    sa.Column('ferramenta_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.Enum('pendente', 'confirmada', 'recusada', name='statustransferencia'), nullable=True),
    sa.Column('data_envio', sa.DateTime(), nullable=True),
    sa.Column('data_confirmacao', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['ferramenta_id'], ['ferramentas.id'], ),
    sa.ForeignKeyConstraint(['material_id'], ['materiais.id'], ),
    sa.ForeignKeyConstraint(['tecnico_id'], ['tecnicos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('monitor_dispositivos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('unidade_id', sa.Integer(), nullable=False),
    sa.Column('codigo', sa.String(), nullable=False),
    sa.Column('nome', sa.String(), nullable=False),
    sa.Column('fabricante', sa.String(), nullable=False),
    sa.Column('ip_wireguard', sa.String(), nullable=False),
    sa.Column('ativo', sa.Boolean(), nullable=False),
    sa.Column('criado_em', sa.DateTime(), nullable=False),
    sa.Column('atualizado_em', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['unidade_id'], ['monitor_unidades.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('codigo'),
    sa.UniqueConstraint('ip_wireguard')
    )
    op.create_table('monitor_links',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('dispositivo_id', sa.Integer(), nullable=False),
    sa.Column('codigo', sa.String(), nullable=False),
    sa.Column('nome', sa.String(), nullable=False),
    sa.Column('if_index', sa.Integer(), nullable=False),
    sa.Column('operadora', sa.String(), nullable=False),
    sa.Column('papel', sa.String(), nullable=False),
    sa.Column('ativo', sa.Boolean(), nullable=False),
    sa.Column('criado_em', sa.DateTime(), nullable=False),
    sa.Column('atualizado_em', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['dispositivo_id'], ['monitor_dispositivos.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('dispositivo_id', 'codigo', name='uq_monitor_link_codigo_dispositivo'),
    sa.UniqueConstraint('dispositivo_id', 'if_index', name='uq_monitor_link_ifindex_dispositivo')
    )
    op.create_table('monitor_testes_configuracao',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('dispositivo_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('sucesso', sa.Boolean(), nullable=True),
    sa.Column('resultado', sa.Text(), nullable=True),
    sa.Column('solicitado_em', sa.DateTime(), nullable=False),
    sa.Column('iniciado_em', sa.DateTime(), nullable=True),
    sa.Column('finalizado_em', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['dispositivo_id'], ['monitor_dispositivos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('monitor_ocorrencias',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ordem_id', sa.Integer(), nullable=False),
    sa.Column('unidade_id', sa.Integer(), nullable=False),
    sa.Column('dispositivo_id', sa.Integer(), nullable=False),
    sa.Column('link_id', sa.Integer(), nullable=True),
    sa.Column('tipo', sa.String(), nullable=False),
    sa.Column('inicio', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['dispositivo_id'], ['monitor_dispositivos.id'], ),
    sa.ForeignKeyConstraint(['link_id'], ['monitor_links.id'], ),
    sa.ForeignKeyConstraint(['ordem_id'], ['ordens_servico.id'], ),
    sa.ForeignKeyConstraint(['unidade_id'], ['monitor_unidades.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ordem_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('monitor_ocorrencias')
    op.drop_table('monitor_testes_configuracao')
    op.drop_table('monitor_links')
    op.drop_table('monitor_dispositivos')
    op.drop_table('transferencias')
    op.drop_table('movimentacoes_estoque')
    op.drop_table('monitor_unidades')
    op.drop_table('fotos_ordem')
    op.drop_table('avisos_ferramentas')
    op.drop_table('solicitacoes_material')
    op.drop_table('ordens_servico')
    op.drop_table('monitor_clientes')
    op.drop_table('ferramentas')
    op.drop_table('estoque_pessoal')
    op.drop_table('tecnicos')
    op.drop_table('materiais')
    op.drop_table('contas_financeiras')
    op.drop_table('clientes')
    op.drop_table('admin_usuarios')

    if op.get_bind().dialect.name == 'postgresql':
        for nome in (
            'statustransferencia',
            'tipotransferencia',
            'tipomovimentacao',
            'statusaviso',
            'statussolicitacao',
            'statusos',
            'tipoos',
            'statusferramenta',
            'categoriaferramenta',
            'statusconta',
            'tipoconta',
            'papeladmin',
        ):
            sa.Enum(name=nome).drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
